### ISSUE TITLE
Error upon run

### ISSUE THREAD

**Issue by JustinCarr** [cfculhane/AnkiOCR#13]
Ive been using this addon for a month now, and it works great. The update on 1/19/20 has created an error for me (no longer runs). See below:

Caught exception:
Traceback (most recent call last):
  File "/Users/-----------/Library/Application Support/Anki2/addons21/450181164/gui.py", line 108, in <lambda>
    act_run_ocr.triggered.connect(lambda b=browser: on_run_ocr(browser))
  File "/Users/-----------/Library/Application Support/Anki2/addons21/450181164/gui.py", line 24, in on_run_ocr
    num_batches = ceil(num_notes / config["batch_size"])
TypeError: 'NoneType' object is not subscriptable

**Comment by cfculhane** [comment]
Ahh thanks for this, will push an update tonight!

**Comment by cfculhane** [comment]
Fixed in 0.4.3
