### ISSUE TITLE
AttributeError: 'ErrorHandler' object has no attribute 'flush'

### ISSUE THREAD

**Issue by onexming** [cfculhane/AnkiOCR#14]
Anki 2.1.35 (84dcaa86) Python 3.9.1 Qt 5.15.2 PyQt 5.15.2
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-01-28 23:51:24

Error encountered during processing, attempting to stop AnkiOCR gracefully. Error below:
Traceback (most recent call last):
   File "/home/onexming/.local/share/Anki2/addons21/450181164/gui.py", line 54, in on_run_ocr
    ocr.run_ocr_on_notes(note_ids=selected_nids)
   File "/home/onexming/.local/share/Anki2/addons21/450181164/ocr.py", line 303, in run_ocr_on_notes
    notes_query = self.run_ocr_on_query(query=query_str)
   File "/home/onexming/.local/share/Anki2/addons21/450181164/ocr.py", line 272, in run_ocr_on_query
    raw_results = self._ocr_batch_process(batched_txts=batched_txts)
   File "/home/onexming/.local/share/Anki2/addons21/450181164/ocr.py", line 78, in _ocr_batch_process
    pbar = tqdm(total=num_batches) if ANKI_ENV is False else None
   File "/home/onexming/.local/lib/python3.9/site-packages/tqdm/std.py", line 1092, in __init__
    self.refresh(lock_args=self.lock_args)
   File "/home/onexming/.local/lib/python3.9/site-packages/tqdm/std.py", line 1386, in refresh
    self.display()
   File "/home/onexming/.local/lib/python3.9/site-packages/tqdm/std.py", line 1519, in display
    self.moveto(pos)
   File "/home/onexming/.local/lib/python3.9/site-packages/tqdm/std.py", line 1475, in moveto
    self.fp.flush()
   File "/home/onexming/.local/lib/python3.9/site-packages/tqdm/utils.py", line 169, in __getattr__
    return getattr(self._wrapped, name)
 AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by cfculhane** [comment]
Interesting, thi slooks like it was trying to grab the tqdm from your local python install, which shouldn't be easily done as anki runs inside its own virtual environment... the tqdm is only there for showing an error bar during devlopment
