### ISSUE TITLE
Error - Cannot import q-menu

### ISSUE THREAD

**Issue by bwhurd** [cfculhane/AnkiOCR#26]
I am running anki Version ⁨2.1.45 (6ffa7440)⁩ Python 3.9.0 Qt 5.15.2 PyQt 5.15.4.

On startup, I receive the following error:
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨AnkiOCR⁩':
⁨Traceback (most recent call last):
  File "c:\pyenv\lib\site-packages\aqt\addons.py", line 217, in loadAddons
    __import__(addon.dir_name)
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\450181164\__init__.py", line 6, in <module>
    from . import gui
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\450181164\gui.py", line 7, in <module>
    from aqt.browser import Browser, QMenu
ImportError: cannot import name 'QMenu' from 'aqt.browser' (c:\pyenv\lib\site-packages\aqt\browser\__init__.py)
```
Let me know if you need more info. I wasn't sure what to put in the issue title of this post.

**Comment by cfculhane** [comment]
Thanks for the bug report, this is sufficient don't worry! When I get a chance I'll update this, it should be an easy fix, just an Anki API change that happened

**Comment by cfculhane** [comment]
This is now fixed in the latest release!
