### ISSUE TITLE
setting        ''new_field''    option in config throws error when OCR run

### ISSUE THREAD

**Issue by JEREMIAH-2911** [cfculhane/AnkiOCR#30]
The tooltip option if selected in config ,OCR works fine.     But if i choose new_field , then this error comes.
I just want an easily copyable version of the text within the Image available in usual study window itself...Its difficult to go to browser each time i want to copy paste the title tooltip by opening HTML VIEWER.

***************
A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 8.1
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2021-09-18 14:36:06

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 54, in handler
  File "aqt\utils.py", line 962, in <lambda>
  File "aqt\browser\browser.py", line 421, in onRowChanged
  File "aqt\browser\table\table.py", line 83, in get_current_card
  File "aqt\browser\table\model.py", line 177, in get_card
  File "aqt\browser\table\state.py", line 142, in get_card
  File "anki\collection.py", line 315, in get_card
  File "anki\cards.py", line 59, in __init__
  File "anki\cards.py", line 67, in load
  File "anki\_backend\generated.py", line 930, in get_card
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by cfculhane** [comment]
Hi there, I couldn't reproduce this on my machine. From looking around, it seems like it might be a database issue : https://forums.ankiweb.net/t/error-on-anki-2-1-43/9890

Does this happen after restarting your computer?

**Comment by JEREMIAH-2911** [comment]
I switched off and again switch on laptop. Updated to todays new version of Anki OCR . Checked my database. Still error Persists

A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 8.1
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2021-09-19 15:51:09

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 54, in handler
  File "aqt\utils.py", line 962, in <lambda>
  File "aqt\browser\browser.py", line 421, in onRowChanged
  File "aqt\browser\table\table.py", line 83, in get_current_card
  File "aqt\browser\table\model.py", line 177, in get_card
  File "aqt\browser\table\state.py", line 142, in get_card
  File "anki\collection.py", line 315, in get_card
  File "anki\cards.py", line 59, in __init__
  File "anki\cards.py", line 67, in load
  File "anki\_backend\generated.py", line 930, in get_card
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by pranav517517** [comment]
A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Platform: Mac 12.4
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-08-28 12:17:36

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.utils", line 1018, in <lambda>
  File "aqt.browser.browser", line 466, in on_all_or_selected_rows_changed
  File "aqt.browser.table.table", line 105, in get_single_selected_card
  File "aqt.browser.table.model", line 222, in get_card
  File "aqt.browser.table.state", line 147, in get_card
  File "anki.collection", line 410, in get_card
  File "anki.cards", line 60, in __init__
  File "anki.cards", line 68, in load
  File "anki._backend.generated", line 1800, in get_card
  File "anki._backend", line 140, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

same issue with me it my system config are
os-mac os monterey
version-12.4
chip architecture-m1 apple silicon

i will try once more in with all addon disabled except ankiocr and will also try on cisc x86 architecture and update over here whether the issue is in arm architecture only. this happened when i changed config from tooltip to new_field i also added the new_field in note type still i face this error.

**Comment by abhishek7786** [comment]
@pranav517517 @JEREMIAH-2911 Did you guys had any success with solving the new_field issue ?

@cfculhane, thanks for the amazing addon, can you please help in resolving this ?

I've tons of screenshot as anki card,,, this would be very helpful in performing search among the card.

I've tried this forked version 
https://ankiweb.net/shared/info/546383173

Error Details - 
https://pastebin.com/YuHY6iyJ

Platform details -

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.1.1-arm64-arm-64bit

**Comment by pranav517517** [comment]
> @pranav517517 @JEREMIAH-2911 Did you guys had any success with solving the new_field issue ?
> 
> @cfculhane, thanks for the amazing addon, can you please help in resolving this ?
> 
> I've tons of screenshot as anki card,,, this would be very helpful in performing search among the card.
> 
> I've tried this forked version https://ankiweb.net/shared/info/546383173
> 
> Error Details - https://pastebin.com/YuHY6iyJ
> 
> Platform details -
> 
> Anki 24.06.3 (d678e393) (ao) Python 3.9.18 Qt 6.6.2 PyQt 6.6.1 Platform: macOS-14.1.1-arm64-arm-64bit

bro i am not an engineer. I am also studying.
