### ISSUE TITLE
AnkiOCR crashes on "new_field" output option

### ISSUE THREAD

**Issue by hienstorfer** [cfculhane/AnkiOCR#37]
Hello Chris,
Anki OCR is working for me as long as I use "tooltip" option as output location.
When I am switching to "new_field", Anki is crashing.
Is there a solution?
regards,
Philipp

=================
*configuration*
{
    "batch_size": 5,
    "languages": [
        "rus"
    ],
    "num_threads": 2,
    "override_tesseract_exec": false,
    "overwrite_existing": true,
    "tesseract_exec_path": "",
    "tesseract_install_valid": true,
    "text_output_location": "new_field",
    "use_batching": true,
    "use_multithreading": true
}

============================
A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2023-02-14 21:51:13

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.utils", line 1188, in <lambda>
  File "aqt.browser.browser", line 542, in on_all_or_selected_rows_changed
  File "aqt.browser.table.table", line 103, in get_single_selected_card
  File "aqt.browser.table.model", line 222, in get_card
  File "aqt.browser.table.state", line 148, in get_card
  File "anki.collection", line 462, in get_card
  File "anki.cards", line 60, in __init__
  File "anki.cards", line 68, in load
  File "anki._backend_generated", line 1844, in get_card
  File "anki._backend", line 150, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by miahen** [comment]
having the same issue. 

A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2023-02-20 13:47:17

bs4:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
Caught exception:
Traceback (most recent call last):
  File "aqt.browser.table.table", line 387, in _on_current_changed
  File "aqt.browser.browser", line 567, in on_current_row_changed
  File "aqt.browser.table.table", line 93, in get_current_card
  File "aqt.browser.table.model", line 222, in get_card
  File "aqt.browser.table.state", line 148, in get_card
  File "anki.collection", line 463, in get_card
  File "anki.cards", line 60, in __init__
  File "anki.cards", line 68, in load
  File "anki._backend_generated", line 1866, in get_card
  File "anki._backend", line 150, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Caught exception:
Traceback (most recent call last):
  File "C:\Users\CNJAR\AppData\Roaming\Anki2\addons21\450181164\gui.py", line 124, in <lambda>
    act_run_ocr.triggered.connect(lambda b=browser: on_run_ocr(browser))
  File "C:\Users\CNJAR\AppData\Roaming\Anki2\addons21\450181164\gui.py", line 95, in on_run_ocr
    mw.requireReset()
  File "aqt.main", line 837, in requireReset
  File "aqt.main", line 822, in reset
  File "aqt.main", line 774, in _synthesize_op_did_execute_from_reset
  File "_aqt.hooks", line 3547, in __call__
  File "aqt.browser.browser", line 186, in on_operation_did_execute
  File "aqt.browser.table.table", line 93, in get_current_card
  File "aqt.browser.table.model", line 222, in get_card
  File "aqt.browser.table.state", line 148, in get_card
  File "anki.collection", line 463, in get_card
  File "anki.cards", line 60, in __init__
  File "anki.cards", line 68, in load
  File "anki._backend_generated", line 1866, in get_card
  File "anki._backend", line 150, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.sync", line 49, in on_future_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.sync", line 58, in <lambda>
  File "anki.collection", line 1208, in sync_status
  File "anki._backend_generated", line 773, in sync_status
  File "anki._backend", line 150, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
