### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fingreg** [cfculhane/AnkiOCR#43]
Hi, AnkiOCR doesn't work, I have this error when trying to run it on a note. It only works when I run it on a note without image lol 

Error encountered during processing. Debug info: 
Anki Version: 2.1.65 , AnkiOCR Version: 0.7.1
Platform: Darwin , Python Version: 3.9.15 (main, Nov  6 2022, 11:31:59) 
[Clang 14.0.3 ]Traceback (most recent call last):
  File "/Users/greg/Library/Application Support/Anki2/addons21/450181164/gui.py", line 58, in on_run_ocr
    ocr.run_ocr_on_notes(note_ids=selected_nids)
  File "/Users/greg/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 309, in run_ocr_on_notes
    notes_query = self.run_ocr_on_query(note_ids=note_ids)
  File "/Users/greg/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 277, in run_ocr_on_query
    batched_txts, batched_txts_dir, batch_mapping = self._gen_batched_txts(notes_to_process=notes_query.notes,
  File "/Users/greg/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 228, in _gen_batched_txts
    batch_txt_pth.write_text("\n".join([str(i.img_pth) for i in batched_imgs]))
  File "pathlib", line 1286, in write_text
UnicodeEncodeError: 'ascii' codec can't encode characters in position 86-87: ordinal not in range(128)

Can you help me please ? I'm on macOS 14.0

**Comment by kcrimson1** [comment]
我已经成功了!!!!

感谢你对这个插件作出的努力, 让我一个电脑小白能够使用anki的高阶功能!!!!

祝你生活愉快
