### ISSUE TITLE
Addon Install Error : No module named 'PyQt5

### ISSUE THREAD

**Issue by xXWarMachineRoXx** [cfculhane/AnkiOCR#45]
## Error Log 
```py

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-17 23:10:32

When loading AnkiOCR:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\450181164\__init__.py", line 6, in <module>
    from . import gui
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\450181164\gui.py", line 6, in <module>
    from PyQt5.QtWidgets import QMenu
ModuleNotFoundError: No module named 'PyQt5'

```

## Remarks
I know the error is simple to resolve but I think its better for the addon to install modules by themselves 

a simple 

```py 
pip install PyQt5
```

will fix it but I don't know if there would be more errors after that.

@cfculhane please look into it , this hasn't been updated in a long time.

**Comment by cfculhane** [comment]
This is now being worked on, fix is on master, will release this week :)

**Comment by inww7** [comment]
> 现在正在处理中，修复在master上，将于本周发布:)

嘿! 我相信一定有很多人正期待着你的插件的重新焕发. 

如果下次更新能够修复"new_field"的问题就更好了. 

以下是我的报错
-----
A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2024-01-01 05:39:58

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.utils", line 1205, in <lambda>
  File "aqt.browser.browser", line 546, in on_all_or_selected_rows_changed
  File "aqt.browser.table.table", line 103, in get_single_selected_card
  File "aqt.browser.table.model", line 222, in get_card
  File "aqt.browser.table.state", line 148, in get_card
  File "anki.collection", line 507, in get_card
  File "anki.cards", line 60, in __init__
  File "anki.cards", line 68, in load
  File "anki._backend_generated", line 1867, in get_card
  File "anki._backend", line 150, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by ColoursB** [comment]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.5-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-01-05 10:08:23

When loading AnkiOCR:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/__init__.py", line 6, in <module>
    from . import gui
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/gui.py", line 6, in <module>
    from PyQt5.QtWidgets import QMenu
ModuleNotFoundError: No module named 'PyQt5'

**Comment by xXWarMachineRoXx** [comment]
> Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3 Platform: macOS-13.5-arm64-arm-64bit Flags: frz=True ao=True sv=3 Add-ons, last update check: 2024-01-05 10:08:23
> 
> When loading AnkiOCR: Traceback (most recent call last): File "aqt.addons", line 245, in loadAddons File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/**init**.py", line 6, in from . import gui File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/gui.py", line 6, in from PyQt5.QtWidgets import QMenu ModuleNotFoundError: No module named 'PyQt5'

hi @ColoursB,
Its seems you have the same error, But your trying to install on Mac right?
Can you open up terminal and type `python` ( to check you have python installed)
and then type `import PyQt5`

like this 
<img width="768" alt="image" src="https://github.com/cfculhane/AnkiOCR/assets/47086987/c80f16aa-8c34-4cdf-951d-897c80dd310d">

Let me know what output you get.

**Comment by ColoursB** [comment]
@xXWarMachineRoXx 
Python 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:38) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

Also, on attempting an upload from file, this is the error I get
<img width="464" alt="Screenshot 2024-01-06 at 20 00 36" src="https://github.com/cfculhane/AnkiOCR/assets/6841977/b5f9b107-50aa-4150-88fc-c6760a11335e">
<img width="876" alt="Screenshot 2024-01-06 at 20 01 05" src="https://github.com/cfculhane/AnkiOCR/assets/6841977/e8264c58-de95-4bb3-a1e8-22f83bcb8291">

**Comment by xXWarMachineRoXx** [comment]
@ColoursB Sorry I didn't realize that I didn't quite put it so clearly 

I meant :

1. Go to terminal and type `python`.
2. press `Command + Z  ` or `exit()` to exit.
3. Then Enter `pip install PyQt5`

> But I have realized the real root of the problem.
> @cfculhane, I think you will like this too.

Anki Comes in 2 versions 🔢 :

🍎 **macOS**
-  _With Qt6_
<a href="https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-mac-apple-qt6.dmg" class="btn btn-large">Download Anki for macOS 12+ (Apple Silicon, 23.12.1 Qt6)</a>

-  _With Qt5_
<a href="https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-mac-intel-qt5.dmg" class="btn">Download Anki for macOS 10.13.4+ (Intel, 23.12.1 Qt5)</a>

🪟 **Windows**
-  _With Qt6_
[Download Anki for Windows 10/11 (23.12.1 Qt6)](https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-windows-qt6.exe)
- _With Qt5_
[Download Anki for Windows 10/11 (23.12.1 Qt5)](https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-windows-qt5.exe)

And to solve this Isssue #45 `No Module Named Qt5`, we need to install the anki with PyQt5.
💥 Boom Solved

**Comment by ColoursB** [comment]
Thanks for the tip @xXWarMachineRoXx, I've installed the Qt5 version and it *almost* works perfectly! I'm able to run the addon now, however am now getting the following error with some (but not all) cards.

```
Error encountered during processing. Debug info: 
Anki Version: 23.12.1 , AnkiOCR Version: 0.7.1
Platform: Darwin , Python Version: 3.9.15 (main, Nov  6 2022, 09:08:57) 
[Clang 14.0.3 ]Traceback (most recent call last):
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/gui.py", line 58, in on_run_ocr
    ocr.run_ocr_on_notes(note_ids=selected_nids)
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 309, in run_ocr_on_notes
    notes_query = self.run_ocr_on_query(note_ids=note_ids)
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 277, in run_ocr_on_query
    batched_txts, batched_txts_dir, batch_mapping = self._gen_batched_txts(notes_to_process=notes_query.notes,
  File "/Users/camilleroney/Library/Application Support/Anki2/addons21/450181164/ocr.py", line 228, in _gen_batched_txts
    batch_txt_pth.write_text("\n".join([str(i.img_pth) for i in batched_imgs]))
  File "pathlib", line 1286, in write_text
UnicodeEncodeError: 'ascii' codec can't encode character '\u202f' in position 110: ordinal not in range(128)
```

To answer your previous prompt, here's what I get in terminal.
```
Last login: Tue Jan  9 10:06:55 on ttys000
camilleroney@Camilles-MacBook-Pro ~ % python3
Python 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:38) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
camilleroney@Camilles-MacBook-Pro ~ % pip3 install PyQt5
Requirement already satisfied: PyQt5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (5.15.10)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from PyQt5) (12.13.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from PyQt5) (5.15.12)
camilleroney@Camilles-MacBook-Pro ~ % 
```

**Comment by xXWarMachineRoXx** [comment]
I'm glad that is working now

I see that is not able to format a unicode but mostly your problem has been solved


I however don't consider it fully solved, ill make some changes to the code to make it work with pyqt6 in feb. 


I don't have access to a computer right now but ill look into that error of yours

**Comment by cfculhane** [comment]
@xXWarMachineRoXx  - I have given you access to this repo, I'm sorry that I do not have the time to maintain this repo at this time. I can help push out a release when the major issues are fixed though, to keep the continuinity of the plugin on AnkiHub

**Comment by xXWarMachineRoXx** [comment]
@cfculhane 

hey, I couldn't accept the invite in time and its expired now.
can you send it again?

**Comment by cfculhane** [comment]
done :)

**Comment by xXWarMachineRoXx** [comment]
I'm in !

i think so!

**Comment by Mavsfan77** [comment]
@xXWarMachineRoXx @cfculhane Thanks so much for working on this! this add on is the absolute greatest. I stupidly updated anki yesterday and I made a ton of cards yesterday (on the pyqt6) wont work for OCR addon. Otherwise it works perfectly. Is there any way this could get fixed sooner than later?

**Comment by xXWarMachineRoXx** [comment]
@Mavsfan77 

as I said before, I would port it to qt 6. I have important exams and work stuff going on. But, after Feb 13th, I will be available to do stuff.

**Comment by Mavsfan77** [comment]
any update on a fix?

**Comment by shigeyukey** [comment]
I tried to fix this add-on for PyQt6, so far it works on Windows, but does not work on Mac.
(freezes or crashes without error).
https://ankiweb.net/shared/info/546383173
This add-on bundles something for Mac, so could that be the cause? I am not sure of the cause.

**Comment by xXWarMachineRoXx** [comment]
@Mavsfan77, sorry been real busy. I also was thinking, it would be difficult for me to check for Mac issues. @shigeyukey says that Windows is working it seems?

**Comment by abhishek7786** [comment]
@xXWarMachineRoXx @shigeyukey I tried the ported addon in mac it runs with 'tooltip' option but fails with 'new_field' option.
Here is the detailed information about the issue I'm encountering.

https://github.com/cfculhane/AnkiOCR/issues/30#issuecomment-2434464171

can you guys please provide few pointers to solve this issue.

In case any more logs are needed please let me know.

**Comment by shigeyukey** [comment]
Thanks for the mention, I haven't looked into that issue yet. My fixed version (fork) has a lot of low ratings so it's a pretty low priority for development (plus I'm a Windows user so I only debug Mac occasionally), but this add-on is useful and interesting so I will look into it again later, please wait.

**Comment by abhishek7786** [comment]
@shigeyukey Thanks for looking into it; in case you need any logs from mac machine let me know.

**Comment by khesed** [comment]
@shigeyukey still planning on debugging Mac?

**Comment by shigeyukey** [comment]
Yes, I'm in the process of looking into it, please wait.
